name: Test

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: genereate release note
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            with open('./RELEASE_NOTE.txt', 'w', encoding='utf-8') as file:
              file.write(f'''
              * mpv version: ddd
              * ffmpeg version: v444.
              * placebo version: 444
              ''')


      - name: Install dependencies
        run: |
          echo 'ddddd' > aaaa.txt

          
      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: test
          tag_name: test
          files: |
            ./aaaa.txt
          body_path: ./RELEASE_NOTE.txt
          generate_release_notes: true
          fail_on_unmatched_files: true
          
